server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://123.249.20.245:3306/simon?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: simon
    password: f3ALMbFCDnyeKwpK
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    default-property-inclusion: non_null
  security:
    basic:
      enabled: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.simon.entity
  type-handlers-package: com.example.simon.typehandler
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  expiration: 86400000  # 24小时

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /api-docs/swagger-config
    urls:
      - url: /api-docs
        name: API docs
  packages-to-scan: com.example.simon.controller 